<?xml version="1.0"?>
<package format="3">
  <name>l1_tf_bringup</name>
  <version>0.0.1</version>
  <description>Bringup package for Unitree L1 static TF extrinsics (base_link -> unilidar_lidar).</description>

  <maintainer email="wingsmm@qq.com">wingsmm</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>tf2_ros</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

