unitree_lidar_ros2_node:
  ros__parameters:
    port: "/dev/unilidar_serial4"
    rotate_yaw_bias: 0.0
    range_scale: 0.001
    range_bias: 0.0
    range_max: 50.0
    range_min: 0.0
    cloud_frame: "unilidar_lidar"
    cloud_topic: "unilidar/cloud"
    cloud_scan_num: 18
    imu_frame: "unilidar_imu"
    imu_topic: "unilidar/imu"
